// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsoMANOHd_v3lqcUlvpk704OuHvPdt9I4',
    appId: '1:461271379945:web:fc865977f20e0d5760e578',
    messagingSenderId: '461271379945',
    projectId: 'picnicpal-75f0a',
    authDomain: 'picnicpal-75f0a.firebaseapp.com',
    storageBucket: 'picnicpal-75f0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFTpYfOLqYKWHBVntRlMP59FejsyKBs28',
    appId: '1:461271379945:android:c1933b486f5e8e9860e578',
    messagingSenderId: '461271379945',
    projectId: 'picnicpal-75f0a',
    storageBucket: 'picnicpal-75f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqJq0D1VyfUnA0BxuxoHyodpJt0Ae17ls',
    appId: '1:461271379945:ios:411afc5cddb2735360e578',
    messagingSenderId: '461271379945',
    projectId: 'picnicpal-75f0a',
    storageBucket: 'picnicpal-75f0a.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqJq0D1VyfUnA0BxuxoHyodpJt0Ae17ls',
    appId: '1:461271379945:ios:411afc5cddb2735360e578',
    messagingSenderId: '461271379945',
    projectId: 'picnicpal-75f0a',
    storageBucket: 'picnicpal-75f0a.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsoMANOHd_v3lqcUlvpk704OuHvPdt9I4',
    appId: '1:461271379945:web:20f1fb6798864ce460e578',
    messagingSenderId: '461271379945',
    projectId: 'picnicpal-75f0a',
    authDomain: 'picnicpal-75f0a.firebaseapp.com',
    storageBucket: 'picnicpal-75f0a.appspot.com',
  );
}
